controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

register_app:
    path: /register
    controller: App\Controller\UserController::register
        